spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource.username: 계정
  datasource.password: 암호
  datasource:
    url: jdbc:postgresql://섭/데이터베이스명
  sql:
    init:
      encoding: utf-8
  main:
    allow-bean-definition-overriding: true
server:
  servlet:
    context-path: /api
